### ISSUE TITLE
Úprava firmy bez adresy

### ISSUE THREAD

**Issue by JakubMajzlik** [RA-MPR/mpr#69]
Ak máme firmu, ktorá je bez adresy a odošleme požiadavok na update, ktorý obsahuje adresu, tak backend vráti error. Ak rovnaký požiadavok pošlem pre firmu, ktorá už má adresu, tak to funguje.  

JSON, ktorý som odoslal: 
{"billing_address":{"city":"Test City","street":"Test street","country":"Test Country","zip_code":"12345"}}

Error:

AttributeError at /company/99999999/
'NoneType' object has no attribute 'update'

[response.zip](https://github.com/RA-MPR/mpr/files/6260546/response.zip)

**Comment by mjavorka** [comment]
@JakubMajzlik bug bude opraveny v MR #76 

Ako sa ti vsak podarilo vytvorit company bez adries? V aktualnej verzii su oba polia `contact_address` aj `billing_address` povinne pri vytvarani firmy cez API
