### ISSUE TITLE
GET request for a graph of orders

### ISSUE THREAD

**Issue by HappyC00kie** [RA-MPR/mpr#81]
GET request, který bude vracet sumy provedených objednávek (orders) za jednotlivé měsíce (až rok zpětně) pro daného obchodníka.
Použitím **GET/user/orders** by se získal response, který by obsahoval rozdělení po měsících a k nim sumy provedených objednávek.
Data budou sloužit grafu podepsaných objednávek. 
![image](https://user-images.githubusercontent.com/45210406/113859431-2d47a480-97a5-11eb-9eb7-6bae350d58fc.png)

**Comment by matejmrazik** [comment]
@HappyC00kie prosim ta co myslis tym ze az rok spatna. Ked je napriklad 4.9.2021 a uzivatel posle tento request tak sa mu maju vratit mesiace 10.2020 az 8.2021?

**Comment by HappyC00kie** [comment]
> @HappyC00kie prosim ta co myslis tym ze az rok spatna. Ked je napriklad 4.9.2021 a uzivatel posle tento request tak sa mu maju vratit mesiace 10.2020 az 8.2021?

pochopil jsem to tak, že ke dni 4.9. 2021 by jsme potřebovaly měsíce 10. 2020 až 9. 2021, aby jsme dokázali vykreslit takový graf:
![image](https://user-images.githubusercontent.com/45210406/114428392-6c6a6100-9bbc-11eb-873c-6e345642c57b.png)
