### ISSUE TITLE
contract_number integer conversion

### ISSUE THREAD

**Issue by HappyC00kie** [RA-MPR/mpr#92]
Zkoušel jsem vytvořit objednávku s číslem objednávky 0001, ale vypadá to že BE to převádí do integeru a tím odřeže nuly na začátku. Podle návrhu by měly zůstat.

**Comment by matejmrazik** [comment]
Dobre, viem to opravit len potom nastane problem ze ked da niekto objednavku 0001 a 001 tak pre backend to budu dve rozne objednavky. Nebude nam to vadit?

**Comment by HappyC00kie** [comment]
> Dobre, viem to opravit len potom nastane problem ze ked da niekto objednavku 0001 a 001 tak pre backend to budu dve rozne objednavky. Nebude nam to vadit?

nemělo by, myslím že by se měly považovat za rozdílné
